#! /bin/bash

mysql -uroot -e "CREATE DATABASE `box_django`;"
mysql -uroot -e "CREATE USER 'box'@* IDENTIFIED BY '1234';"
mysql -uroot -e "GRANT ALL PRIVILEGES ON `box_django`.* TO 'box'@*;"
mysql -uroot -e "FLUSH PRIVILEGES;"
